/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.vinni.gui;

import co.vinni.dto.Cliente;
import co.vinni.operaciones.OperCliente;
import java.awt.EventQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

/**
 *
 * @author Vinni
 */
@SpringBootApplication
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cjNombre = new javax.swing.JTextField();
        cjApellido = new javax.swing.JTextField();
        cjTelefono = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CREAR UN CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(104, 20, 140, 14);

        jLabel3.setText("NOMBRE: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 60, 80, 14);

        jLabel4.setText("APELLIDO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 90, 80, 14);

        jLabel5.setText("TELEFONO :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 120, 70, 14);

        jButton1.setText("GUARDAR...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 200, 120, 23);

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 240, 120, 23);

        cjNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjNombreActionPerformed(evt);
            }
        });
        getContentPane().add(cjNombre);
        cjNombre.setBounds(120, 60, 120, 20);
        getContentPane().add(cjApellido);
        cjApellido.setBounds(120, 90, 120, 20);
        getContentPane().add(cjTelefono);
        cjTelefono.setBounds(120, 120, 120, 20);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cjNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
         ConfigurableApplicationContext  ctx = new SpringApplicationBuilder(Ventana.class)
                .headless(false).run(args);

        EventQueue.invokeLater(() -> {

            Ventana ex = (Ventana)ctx.getBean(Ventana.class);
            ex.setVisible(true);
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cjApellido;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void guardar() {
        if (cjNombre.getText().isEmpty() || cjApellido.getText().isEmpty() || cjTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Algún dato esta vacio. !");
            return ;
        }
        OperCliente oper = new OperCliente();
        Cliente cli = new Cliente();
        cli.modNombre(cjNombre.getText());
        cli.modApellido(cjApellido.getText());
        Long telf = 0L;
        try{
            telf = Long.parseLong(cjTelefono.getText().trim());
            cli.modTelefono(telf);
        }catch(NumberFormatException nu){
            
        }
        if (oper.registrar(cli)){
            JOptionPane.showMessageDialog(this, "Se registro el cliente");
        }else{
            JOptionPane.showMessageDialog(this, "No se registro el cliente");

        }
    }
}
